// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "9ak415Vibvtzr7ZZMKXXSwSaJtcd8lw6qBMgQ8YxdBYNTxoAUjVcp4rYpYTkLUiMWaBENA";
}
}
}

